export const cardSixData = [
    {
        level: "BASIC",
        amount: "$ 100 USD",
        desc: "Lorem ipsum dolor sit amet, ametor consectetur adipiscing elit. Et nibh.",
        title: "FEATURES",
        list1: "Everything included in Basic",
        list2: "Trading up to $1MM per month",
        list3: "Windows & macOS App",
        list4: "Premium Support",
    },
    {
        level: "PRO",
        amount: "$ 100 USD",
        desc: "Lorem ipsum dolor sit amet, ametor consectetur adipiscing elit. Et nibh.",
        title: "FEATURES",
        list1: "Everything included in Basic",
        list2: "Trading up to $1MM per month",
        list3: "Windows & macOS App",
        list4: "Premium Support",
    },
    {
        level: "EXPERT",
        amount: "$ 100 USD",
        desc: "Lorem ipsum dolor sit amet, ametor consectetur adipiscing elit. Et nibh.",
        title: "FEATURES",
        list1: "Everything included in Basic",
        list2: "Trading up to $1MM per month",
        list3: "Windows & macOS App",
        list4: "Premium Support",
    },
]